In [2]:
import numpy as np

question01

In [12]:
array_01=np.arange(1,13)

In [13]:
array_01

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

question02

In [14]:
array_01.dtype

dtype('int64')

question03

In [15]:
array_03=array_01.reshape(3,4)

In [16]:
array_03

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

question04

In [17]:
array_03.shape

(3, 4)

question05

In [23]:
array_03[1][1]

np.int64(6)

In [24]:
print(array_03[1][1])

6


question06

In [25]:
array_06=array_03*2

In [28]:
array_06

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

question07

In [31]:
res=array_06+5

In [32]:
print(res)

[[ 7  9 11 13]
 [15 17 19 21]
 [23 25 27 29]]


In [39]:
array_07=np.zeros(18)
array_07

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [38]:
array_08=np.ones(20)*4
array_08

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4.])

In [44]:
array_09=np.arange(21)
array_09

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [40]:
array_10=np.random.random(24)
array_10

array([0.48695778, 0.35578883, 0.47544472, 0.07356828, 0.86954881,
       0.94702559, 0.11289822, 0.20426309, 0.50136154, 0.83829505,
       0.97828343, 0.98634002, 0.47776871, 0.89862327, 0.77165072,
       0.48648027, 0.4182777 , 0.30801869, 0.75585298, 0.41085973,
       0.57033668, 0.75158985, 0.01593915, 0.62828522])

In [42]:
array_10.reshape(6,4)

array([[0.48695778, 0.35578883, 0.47544472, 0.07356828],
       [0.86954881, 0.94702559, 0.11289822, 0.20426309],
       [0.50136154, 0.83829505, 0.97828343, 0.98634002],
       [0.47776871, 0.89862327, 0.77165072, 0.48648027],
       [0.4182777 , 0.30801869, 0.75585298, 0.41085973],
       [0.57033668, 0.75158985, 0.01593915, 0.62828522]])

In [45]:
array_11=array_08.astype(str)
array_11

array(['4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0',
       '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0',
       '4.0', '4.0'], dtype='<U32')

In [56]:
array_12=array_11.astype(float).astype(int)
array_12.sum(axis=0)


np.int64(80)