In [4]:
import numpy as np

qustion13

In [13]:
array_10=np.random.random(24)
array_010=array_10.reshape(6,4)
array_010

array([[0.23422419, 0.3226003 , 0.58247349, 0.24748726],
       [0.84020275, 0.40646892, 0.41274716, 0.89869005],
       [0.80138335, 0.39417676, 0.45076254, 0.38472801],
       [0.83907965, 0.00921011, 0.88108639, 0.76265059],
       [0.61725002, 0.70686102, 0.38194167, 0.88583304],
       [0.7200417 , 0.14781739, 0.53738791, 0.25908124]])

In [14]:
array_14=array_010.astype(float)
array_14

array([[0.23422419, 0.3226003 , 0.58247349, 0.24748726],
       [0.84020275, 0.40646892, 0.41274716, 0.89869005],
       [0.80138335, 0.39417676, 0.45076254, 0.38472801],
       [0.83907965, 0.00921011, 0.88108639, 0.76265059],
       [0.61725002, 0.70686102, 0.38194167, 0.88583304],
       [0.7200417 , 0.14781739, 0.53738791, 0.25908124]])

In [15]:
array_14.sum(axis=1)

array([1.38678524, 2.55810888, 2.03105065, 2.49202674, 2.59188576,
       1.66432824])

qustion14

In [17]:
array_010[::-1]

array([[0.7200417 , 0.14781739, 0.53738791, 0.25908124],
       [0.61725002, 0.70686102, 0.38194167, 0.88583304],
       [0.83907965, 0.00921011, 0.88108639, 0.76265059],
       [0.80138335, 0.39417676, 0.45076254, 0.38472801],
       [0.84020275, 0.40646892, 0.41274716, 0.89869005],
       [0.23422419, 0.3226003 , 0.58247349, 0.24748726]])

qustion15

In [21]:
array_15=np.array([1,2,3,4,5,6])
arra_00=array_15.reshape(6,1)
print(array_010+arra_00)

[[1.23422419 1.3226003  1.58247349 1.24748726]
 [2.84020275 2.40646892 2.41274716 2.89869005]
 [3.80138335 3.39417676 3.45076254 3.38472801]
 [4.83907965 4.00921011 4.88108639 4.76265059]
 [5.61725002 5.70686102 5.38194167 5.88583304]
 [6.7200417  6.14781739 6.53738791 6.25908124]]


qustion16

In [22]:
print(array_010[:,1::2])

[[0.3226003  0.24748726]
 [0.40646892 0.89869005]
 [0.39417676 0.38472801]
 [0.00921011 0.76265059]
 [0.70686102 0.88583304]
 [0.14781739 0.25908124]]


In [23]:
print(array_010[:,0::2])

[[0.23422419 0.58247349]
 [0.84020275 0.41274716]
 [0.80138335 0.45076254]
 [0.83907965 0.88108639]
 [0.61725002 0.38194167]
 [0.7200417  0.53738791]]


qustion17

In [24]:
array_17=np.zeros(9)
array_17.reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

qustion18

In [25]:
array_18=np.sort(array_010)
array_18

array([[0.23422419, 0.24748726, 0.3226003 , 0.58247349],
       [0.40646892, 0.41274716, 0.84020275, 0.89869005],
       [0.38472801, 0.39417676, 0.45076254, 0.80138335],
       [0.00921011, 0.76265059, 0.83907965, 0.88108639],
       [0.38194167, 0.61725002, 0.70686102, 0.88583304],
       [0.14781739, 0.25908124, 0.53738791, 0.7200417 ]])

qustion19

In [26]:
print(array_010.T)

[[0.23422419 0.84020275 0.80138335 0.83907965 0.61725002 0.7200417 ]
 [0.3226003  0.40646892 0.39417676 0.00921011 0.70686102 0.14781739]
 [0.58247349 0.41274716 0.45076254 0.88108639 0.38194167 0.53738791]
 [0.24748726 0.89869005 0.38472801 0.76265059 0.88583304 0.25908124]]


qusetion20

In [29]:
array_20=np.arange(12,57,2)
array_20

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44,
       46, 48, 50, 52, 54, 56])