In [1]:
import numpy as np

QUESTION_01

In [9]:
arr=np.arange(-60,61)
arr

array([-60, -59, -58, -57, -56, -55, -54, -53, -52, -51, -50, -49, -48,
       -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35,
       -34, -33, -32, -31, -30, -29, -28, -27, -26, -25, -24, -23, -22,
       -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,
        -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,
         5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60])

In [10]:
array_01=np.where(arr%2!=0,-1,arr)
array_01

array([-60,  -1, -58,  -1, -56,  -1, -54,  -1, -52,  -1, -50,  -1, -48,
        -1, -46,  -1, -44,  -1, -42,  -1, -40,  -1, -38,  -1, -36,  -1,
       -34,  -1, -32,  -1, -30,  -1, -28,  -1, -26,  -1, -24,  -1, -22,
        -1, -20,  -1, -18,  -1, -16,  -1, -14,  -1, -12,  -1, -10,  -1,
        -8,  -1,  -6,  -1,  -4,  -1,  -2,  -1,   0,  -1,   2,  -1,   4,
        -1,   6,  -1,   8,  -1,  10,  -1,  12,  -1,  14,  -1,  16,  -1,
        18,  -1,  20,  -1,  22,  -1,  24,  -1,  26,  -1,  28,  -1,  30,
        -1,  32,  -1,  34,  -1,  36,  -1,  38,  -1,  40,  -1,  42,  -1,
        44,  -1,  46,  -1,  48,  -1,  50,  -1,  52,  -1,  54,  -1,  56,
        -1,  58,  -1,  60])

QUESTION_02

In [15]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 74, 29, 55, 4, 37, 18])
more_arr=np.where(x>y)
more_arr


(array([1, 2, 5, 6, 7, 8, 9]),)

In [16]:
print(x[x>y])

[64 86 55 81 79 90 89]


In [17]:
equal_arr=np.where(x==y)
equal_arr

(array([0, 4]),)

In [18]:
print(x[x==y])

[21 74]


QUESTION_03

In [23]:
array_03=np.random.randint(-10,40,size=(7,24))
print(array_03)

[[ -4  18  14   1  24  18  -6   2  38  31  14  38   2  16  34  21  -6  34
   28  31  26   1  29  -2]
 [ 12  -2   0  30  34   3  22  37  19  32  14  24   8  11  16  23  28  27
   38  39  -4  -2  29  -9]
 [ -7  15  38  -6   1  15   7  20  38  -8  30  19  23  -1  11  17   8  23
    4   9  21  23   3  27]
 [ -9  15  19  15  26   9  22   0  36  -8  19  23   1  28  26  -7 -10  -6
   34   2  19   7  34  19]
 [ 39  24  12   8  16  19   7   2  25  26  26  -6  25  35  32 -10  37  29
   -2  24  33  12  15  25]
 [ 27  -6  22  21   9  19   1   2  38  16  -5  15   8  11  15  -4   4  28
    5  27  -1  35  21  26]
 [ -5  13   6  -6   9  -9  25  11 -10   6  -4  -2  19  29   9   0  22  37
    7  -4  14  36  30 -10]]


In [24]:
array_03_1=np.mean(array_03,axis=0)
array_03_1

array([ 7.57142857, 11.        , 15.85714286,  9.        , 17.        ,
       10.57142857, 11.14285714, 10.57142857, 26.28571429, 13.57142857,
       13.42857143, 15.85714286, 12.28571429, 18.42857143, 20.42857143,
        5.71428571, 11.85714286, 24.57142857, 16.28571429, 18.28571429,
       15.42857143, 16.        , 23.        , 10.85714286])

In [26]:
max_1=np.argmax(array_03_1)
max_1

np.int64(8)

In [27]:
array_03_2=np.mean(array_03,axis=1)
array_03_2

array([16.75      , 17.875     , 13.75      , 13.08333333, 18.875     ,
       13.91666667,  9.29166667])

In [28]:
max_2=np.argmax(array_03_2)
max_2

np.int64(4)

In [29]:
array_03_3=np.max(array_03,axis=1)-np.min(array_03,axis=1)
array_03_3

array([44, 48, 46, 46, 49, 44, 47], dtype=int32)

QUESTION_04

In [30]:
array_04=np.random.randint(0,21,size=(30,5))
print(array_04)

[[17  3 19  3  1]
 [ 8 13 12  4  3]
 [11  7  1 12  9]
 [ 9  0 17  2 14]
 [18  9 16 17  3]
 [ 7  5  4 18 18]
 [15  2  6  6 12]
 [ 8  5 15 12 16]
 [11 11 11 17  4]
 [ 3  7 12  2 11]
 [12  2 11 19 11]
 [ 1 10 20  1 12]
 [19  1 20 19 20]
 [19 18 18 19 13]
 [16  2 13  3 13]
 [ 2  1 20 18  9]
 [13 11  0 20 19]
 [ 7  7  2  9 19]
 [ 9 16  3 19 20]
 [12 15  1 20 17]
 [ 6 10  1 16  1]
 [18 18 10  5  0]
 [20 11  6 12  3]
 [ 9  8  2 20  4]
 [ 7 12 20  4 16]
 [11  8 20  8  8]
 [ 0  4 13  0 12]
 [ 6 17 14  0 18]
 [11  7  7  5  8]
 [20  2  5  6 15]]


In [31]:
array_04_1=np.mean(array_04,axis=1)
array_04_1

array([ 8.6,  8. ,  8. ,  8.4, 12.6, 10.4,  8.2, 11.2, 10.8,  7. , 11. ,
        8.8, 15.8, 17.4,  9.4, 10. , 12.6,  8.8, 13.4, 13. ,  6.8, 10.2,
       10.4,  8.6, 11.8, 11. ,  5.8, 11. ,  7.6,  9.6])

In [32]:
array_04_2=np.mean(array_04,axis=0)
array_04_2

array([10.83333333,  8.06666667, 10.63333333, 10.53333333, 10.96666667])

In [35]:
array_04_3=np.where(array_04>15,True,False)
array_04_3

array([[ True, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [ True, False,  True,  True, False],
       [False, False, False,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [False, False,  True, False, False],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True, False, False, False, False],
       [False, False,  True,  True, False],
       [False, False, False,  True,  True],
       [False, False, False, False,  True],
       [False,  True, False,  True,  True],
       [False, False, False,  True,  True],
       [False, False, False,  True, False],
       [ True,  True, False, False, False],
       [ True, False, False, Fal

In [36]:
array_04_33=np.sum(array_04>15,axis=1)
array_04_33

array([2, 0, 0, 1, 3, 2, 0, 1, 1, 0, 1, 1, 4, 4, 1, 2, 2, 1, 3, 2, 1, 2,
       1, 1, 2, 1, 0, 2, 0, 1])

In [38]:
res=np.where(array_04_33>=3)[0]
res

array([ 4, 12, 13, 18])

In [40]:
array_04_4=np.mean(array_04,axis=0)
array_04_4

array([10.83333333,  8.06666667, 10.63333333, 10.53333333, 10.96666667])

In [41]:
hard_c=np.argmin(array_04_4)
hard_c

np.int64(1)

QUESTION_05

In [42]:
income=np.random.randint(5000,15001,size=12)
expenses=np.random.randint(3000,12001,size=12)
array_05=profit=income-expenses
array_05

array([-4155,  1651,  1420,  6665,  2293,  -192, -1247,  2189,  9576,
         827,   -11,   631], dtype=int32)

In [43]:
array_05_1=np.argmax(array_05)
array_05_1

np.int64(8)

In [51]:
array_05_2=np.where(array_05<0)[0]
array_05_2

array([ 0,  5,  6, 10])